######################################################################
# Automatically generated by qmake (2.01a) Thu May 14 01:37:20 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/xenoterracide/cropt/. .

# Input
HEADERS += connection.h
SOURCES += main.cpp
